---
name: Deploy to PyPi
description: Deploys the python package to PyPi

inputs:
  pypi_api_token:
    description: PyPi api token
    type: string
    required: true

runs:
  using: composite
  steps:
  - name: Get tag release without v
    run: |
      TAG=${{ github.ref_name }}
      echo "VERSION=${TAG#v}" >> "$GITHUB_ENV"
      echo "Tag without v is: ${VERSION}"
  - name: Update Release Tag
    run: sed -i "s/^version = [^ ]*/version = ${{ env.VERSION }}/" setup.cfg
  - name: Set up Python
    uses: actions/setup-python@v3
    with:
      python-version: '3.12.1'
  - name: Install Dependencies
    run: |
      python -m pip install --upgrade pip
      pip install build
  - name: Build Python Package
    run: |
      python -m pip install --upgrade build
      python -m build
  - name: Publish to PyPi
    uses: pypa/gh-action-pypi-publish@release/v1
    with:
      password: ${{ inputs.pypi_api_token }}
      skip-existing: true