name: Test

on:
  pull_request:
    branches: [ "main" ]
    types:
      - opened
      - reopened
      - synchronize

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Python Tests
      uses: ./.github/actions/tests